Immunoprofiling of adenocarcinomas of the pancreatobiliary tree
===============================================================
Immunohistograms - for the resulting clusters and significant markers
=====================================================================

```{r}
suppressMessages(require(ggplot2))
suppressMessages(require(gridExtra))
suppressMessages(require(scales))
suppressMessages(require(plyr))
suppressMessages(require(reshape))

```

File names: clustered dataset
```{r}
myWorkDirectory <- "~/Workspace/research/pcbil/"
clusteredPcbilFileName <- paste(myWorkDirectory, "da/output/clusteredPcbilD.csv", sep="")
```

Importing clustered dataset `r clusteredPcbilFileName` ...
```{r}
pcbilDataClustered <- read.csv(file = clusteredPcbilFileName, row.names = 30, colClasses= c(rep("numeric",27), rep("factor",2), "character"), na.strings = "?",quote="\"" )
```

```{r}
# "extrahepatic-pcbil-tuc vs intrahepatic-ccc-tuc":
extraIntrahepPcbil <- c("maspin", "ca125", "cea_m", "muc5ac", "ck17", "p53", "cdx2", "cd56", "wt1cyt", "vim", "smad4")

# "extrahepatic-pcbil-tuc vs intestinal-tuc":
pcbilIntestinal <- c("ck7", "muc1", "muc5ac", "ck17", "muc2", "ck20", "cdx2")

# "intrahepatic-ccc-tuc vs hcc-tuc":
intrahepHCC <-  c("ck19", "berep4", "ck7",  "muc1", "ca19_9", "vim", "cea_p", "maspin", "wt1cyt", "smad4", "ki67", "cea_m")
```


Simple immunohistograms
```{r fig.width=12, fig.height=8}
diffDiagn1 <- c("extrahepatic-pcbil-tuc", "intestinal-tuc", "intrahepatic-ccc-tuc", "hcc-tuc") # 
diffDiagn2 <- c("intrahepatic-ccc-tuc", "extrahepatic-pcbil-tuc", "extrahepatic-pcbil-tuc", "intrahepatic-ccc-tuc") # 
diffMarkers <- c("ck7", "ck17", "ck19", "ck20", "vim", "muc1", "muc2", "muc5ac", "berep4", "cea_m", "cea_p", "ca19_9", "ca125", "maspin", "cdx2", "p53", "smad4", "cd56", "wt1cyt")
barCol <- c("red", "blueviolet", "blue", "green")


types2Markers <- list("Intermediate filaments" = c("ck7", "ck17", "ck19", "ck20", "vim"),
                      "Mucins" = c("muc1", "muc2", "muc5ac", "muc6"),
                      "Epithelial markers" = c("berep4", "cea_m", "cea_p", "ca19_9", "ca125",  "maspin"),
                      "Nuclear markers" = c("cdx2", "p53", "smad4"),
                      "Other" = c("cd56", "wt1cyt"))

get_marker_type <- function(marker) {
  for(aType in names(types2Markers)) {
       if(marker %in% types2Markers[[aType]]) {
         return(aType)
       }
  }
  return("error")
}

cont <- 1
while(cont <= length(diffDiagn1)){
    
    pcbilTucsQuantit <- subset(pcbilDataClustered, pcbilDataClustered$cluster == diffDiagn1[cont] | pcbilDataClustered$cluster == diffDiagn2[cont])
    pcbilTucs <- pcbilTucsQuantit
  
  for(aMarker in diffMarkers) {
    
    qvals <- pcbilTucs[, aMarker]    
    qvalsCutted <- cut(qvals, c(-1, 10, 100), include.lowest=TRUE, ordered_result=TRUE, labels = c('N', 'P'))
    pcbilTucs[, paste(aMarker, "_cutted", sep='')] <- qvalsCutted      
  }
   
  targetCols <- c(paste(diffMarkers, "_cutted", sep=''), 'cluster')
  pcbilTucsCutted <- pcbilTucs[, targetCols]  
  #pcbilTucs$cluster <- as.factor(as.character(pcbilTucs$cluster))

    # "extrahepatic-pcbil-tuc vs intrahepatic-ccc-tuc": "maspin", "ca125", "cea_m", "muc5ac", "ck17", "p53", "cdx2", "cd56", "wt1cyt", "vim", "smad4"
      pcbilTucsProp <- ddply(pcbilTucsCutted, .(cluster), summarise,
                             ck7 = round(prop.table(table(ck7_cutted)),2) *100,
                             ck17 = round(prop.table(table(ck17_cutted)),2) * 100,
                             ck19 = round(prop.table(table(ck19_cutted)),2) *100,
                             ck20 = round(prop.table(table(ck20_cutted)),2) * 100,
                             vim = round(prop.table(table(vim_cutted)),2) * 100,
                             muc1 = round(prop.table(table(muc1_cutted)),2) * 100,                    
                             muc2 = round(prop.table(table(muc2_cutted)),2) * 100,
                             muc5ac = round(prop.table(table(muc5ac_cutted)),2) * 100,
                             berep4 = round(prop.table(table(berep4_cutted)),2) *100,
                             ca19_9 = round(prop.table(table(ca19_9_cutted)),2) * 100,
                             ca125 = round(prop.table(table(ca125_cutted)),2) * 100,
                             cea_m = round(prop.table(table(cea_m_cutted)),2) * 100,
                             cea_p = round(prop.table(table(cea_p_cutted)),2) * 100,                                                          
                             maspin = round(prop.table(table(maspin_cutted)),2) *100,
                             p53 = round(prop.table(table(p53_cutted)),2) * 100,
                             cdx2 = round(prop.table(table(cdx2_cutted)),2) * 100,                             
                             cd56 = round(prop.table(table(cd56_cutted)),2) * 100,
                             wt1cyt = round(prop.table(table(wt1cyt_cutted)),2) * 100,                             
                             smad4 = round(prop.table(table(smad4_cutted)),2) * 100,
                             score_cats = names(table(ck7_cutted)))
     
    
  pcbilTucsProp$score_cats <- factor(pcbilTucsProp$score_cats, levels = c('N', 'P'))
  posPcbilTucsProp = subset(pcbilTucsProp, score_cats == "P")

  pcbilTucsLong <- melt(posPcbilTucsProp, measure.vars= diffMarkers, variable_name="marker")

  pcbilTucsLong$marker_type <- sapply(pcbilTucsLong$marker, get_marker_type)
  pcbilTucsLong$marker_type <- factor(pcbilTucsLong$marker_type, levels = c('Intermediate filaments', 'Mucins', 'Epithelial markers',  'Nuclear markers', 'Other'))
    
  pcbilTucsLong$marker <- factor(pcbilTucsLong$marker, levels = c(types2Markers[[1]], types2Markers[[2]], types2Markers[[3]], types2Markers[[4]], types2Markers[[5]]))

  
    targetPcbilTucsLong <- subset(pcbilTucsLong, cluster == diffDiagn1[cont])
    
    pl1 <- ggplot(targetPcbilTucsLong, aes(marker, value)) + geom_bar(stat="identity", position="identity", fill= barCol[cont]) + facet_wrap( ~ marker_type, ncol=2, scales="free_x") + xlab("Markers") + ylab("% positive* cases") + ggtitle(paste("Immunohistogram - ",diffDiagn1[cont], sep=""))
     
  labs <- c("")
  g <- tableGrob(labs, gpar.coretext = gpar(fontsize = 10), gpar.corefill = gpar(col = "white"))  # core.just='left' 
    grid.arrange(pl1, g, nrow = 1, ncol = 2, widths = (c(6, 1)))
        
  cont <- cont + 1
}

```

Comparative immunohistograms
```{r fig.width=12, fig.height=8}
diffDiagn1 <- c("extrahepatic-pcbil-tuc", "extrahepatic-pcbil-tuc", "intrahepatic-ccc-tuc") # 
diffDiagn2 <- c("intrahepatic-ccc-tuc", "intestinal-tuc", "hcc-tuc") # 
diffMarkers <- list(
  c("ck17", "muc5ac", "cea_m", "ca125", "maspin", "cdx2", "p53",  "vim",  "smad4",    "cd56", "wt1cyt"),
  c("ck7", "ck17", "muc1", "muc5ac",  "ck20", "muc2",  "cdx2"),
  c("ck7", "ck19", "vim", "muc1", "berep4", "cea_m", "cea_p", "ca19_9",    "maspin",  "ki67", "wt1cyt", "smad4")
  )
parsed_diffMarkers <- list(
  c("CK17", "MUC5Ac", "mCEA", "CA125",  "Maspin", "CDX2", "p53",  "Vim",  "SMAD4",  "CD56", "WT1_cyt"),
  c("CK7", "CK17", "MUC1", "MUC5Ac",  "CK20", "MUC2",  "CDX2"),
  c("CK7", "CK19", "Vim", "MUC1", "BerEP4", "mCEA", "pCEA", "CA19_9",     "Maspin",  "Ki67",  "WT1_cyt", "SMAD4")
  )

compBarCol <- list(c("red", "blue"), c("red", "blueviolet"), c("blue", "green"))

ncols <- c(4,4,4)

cont <- 1
while(cont <= length(diffDiagn1)){
    
    pcbilTucsQuantit <- subset(pcbilDataClustered, pcbilDataClustered$cluster == diffDiagn1[cont] | pcbilDataClustered$cluster == diffDiagn2[cont])
    pcbilTucs <- pcbilTucsQuantit
  
  for(aMarker in diffMarkers[[cont]] ) {
    
    qvals <- pcbilTucs[, aMarker]    
    qvalsCutted <- cut(qvals, c(-1, 10, 100), include.lowest=TRUE, ordered_result=TRUE, labels = c('N',  'P'))
    pcbilTucs[, paste(aMarker, "_cutted", sep = "")] <- qvalsCutted        
  }
   
  targetCols <- c(paste(diffMarkers[[cont]], "_cutted", sep = ""), "cluster")
  pcbilTucsCutted <- pcbilTucs[, targetCols]  
  #pcbilTucs$cluster <- as.factor(as.character(pcbilTucs$cluster))

  if(cont == 1) {
    # "extrahepatic-pcbil-tuc vs intrahepatic-ccc-tuc": "maspin", "ca125", "cea_m", "muc5ac", "ck17", "p53", "cdx2", "cd56", "wt1cyt", "vim", "smad4"
      pcbilTucsProp <- ddply(pcbilTucsCutted, .(cluster), summarise,
                             Maspin = round(prop.table(table(maspin_cutted)),2) *100,
                             CA125 = round(prop.table(table(ca125_cutted)),2) * 100,
                             mCEA = round(prop.table(table(cea_m_cutted)),2) * 100,
                             MUC5Ac = round(prop.table(table(muc5ac_cutted)),2) * 100,
                             CK17 = round(prop.table(table(ck17_cutted)),2) * 100,
                             p53 = round(prop.table(table(p53_cutted)),2) * 100,
                             CDX2 = round(prop.table(table(cdx2_cutted)),2) * 100,
                             CD56 = round(prop.table(table(cd56_cutted)),2) * 100,
                             WT1_cyt = round(prop.table(table(wt1cyt_cutted)),2) * 100,
                             Vim = round(prop.table(table(vim_cutted)),2) * 100,
                             SMAD4 = round(prop.table(table(smad4_cutted)),2) * 100,
                             score_cats = names(table(maspin_cutted)))
  } else if(cont == 2) {
        # "extrahepatic-pcbil-tuc vs intestinal-tuc": "ck7", "muc1", "muc5ac", "ck17", "muc2", "ck20", "cdx2"
        pcbilTucsProp <- ddply(pcbilTucsCutted, .(cluster), summarise,
                             CK7 = round(prop.table(table(ck7_cutted)),2) *100,
                             MUC1 = round(prop.table(table(muc1_cutted)),2) * 100,                    
                             MUC5Ac = round(prop.table(table(muc5ac_cutted)),2) * 100,
                             CK17 = round(prop.table(table(ck17_cutted)),2) * 100,
                             MUC2 = round(prop.table(table(muc2_cutted)),2) * 100,
                             CK20 = round(prop.table(table(ck20_cutted)),2) * 100,
                             CDX2 = round(prop.table(table(cdx2_cutted)),2) * 100,
                             score_cats = names(table(ck7_cutted)))    
  } else if(cont == 3) {
    # "intrahepatic-ccc-tuc vs hcc-tuc": "ck19", "berep4", "ck7",  "muc1", "ca19_9", "vim", "cea_p", "maspin", "wt1cyt", "smad4", "ki67", "cea_m"
      pcbilTucsProp <- ddply(pcbilTucsCutted, .(cluster), summarise,
                             CK19 = round(prop.table(table(ck19_cutted)),2) *100,
                             BerEP4 = round(prop.table(table(berep4_cutted)),2) *100,
                             CK7 = round(prop.table(table(ck7_cutted)),2) *100,
                             MUC1 = round(prop.table(table(muc1_cutted)),2) * 100,
                             CA19_9 = round(prop.table(table(ca19_9_cutted)),2) * 100,
                             Vim = round(prop.table(table(vim_cutted)),2) * 100,
                             pCEA = round(prop.table(table(cea_p_cutted)),2) * 100,                             
                             Maspin = round(prop.table(table(maspin_cutted)),2) *100,
                             WT1_cyt = round(prop.table(table(wt1cyt_cutted)),2) * 100,
                             SMAD4 = round(prop.table(table(smad4_cutted)),2) * 100,
                             Ki67 = round(prop.table(table(ki67_cutted)),2) * 100,
                             mCEA = round(prop.table(table(cea_m_cutted)),2) * 100,                             
                             score_cats = names(table(ck19_cutted)))    
  }    
    
  pcbilTucsProp$score_cats <- factor(pcbilTucsProp$score_cats, levels = c('N', 'P'))

  posPcbilTucsProp = subset(pcbilTucsProp, score_cats == "P")
    
  pcbilTucsLong <- melt(posPcbilTucsProp, measure.vars= parsed_diffMarkers[[cont]], variable_name="marker")
  
  #if(cont == 1) {
  #  pcbilTucsLong$clusterSide <- c(rep(0, 22))
  #} else if(cont == 2) {
  #  pcbilTucsLong$clusterSide <- c(rep(0, 14))
  #} else if(cont == 3) {
  #  pcbilTucsLong$clusterSide <- c(rep(0, 24))
  #}
  
  pl3 <- ggplot(pcbilTucsLong, aes(marker, value, fill= factor(cluster, levels = c("extrahepatic-pcbil-tuc","intrahepatic-ccc-tuc","intestinal-tuc","hcc-tuc") ))) + geom_bar(stat="identity", position="dodge", alpha = 0.85)  + xlab("Positive* immunoreactivity") + ylab("% cases")  + scale_fill_manual("Tumour types",values = compBarCol[[cont]])
    #+ ggtitle("Comparative immunohistogram")
  # + facet_grid( ~ clusterSide, scale = "free")
 
 
 labs <- c("")
 g <- tableGrob(labs, gpar.coretext=gpar(fontsize=10), gpar.corefill=gpar(col="white")) # core.just="left" 
    
    
 grid.arrange(pl3, g, nrow=2, ncol=1, widths=(c(6,1)))
        
        
  cont <- cont + 1
#break;
}

```